#!/usr/bin/env node

var pull = require('pull-stream')
var toPull = require('stream-to-pull-stream')
var Big = require('bignumber.js')

process.stdout.on('error', function( err ) {
    if (err.code == "EPIPE") {
        process.exit(1);
    }
});

var limit = Infinity
if (process.argv.length >= 2 && process.argv[2] != null) {
    limit = Number.parseInt(process.argv[2]) - 1
}

var start = process.argv[3] ? new Big((process.argv[3])) : new Big(0)

pull(
    (limit === 0) ? pull.values([0]) : pull.count(limit),
    pull.map(function (x) { return start.add(x) }),
    pull.map(function (x) { return String(x) + '\n' }),
    toPull.sink(process.stdout)
)
