#!/usr/bin/env node

var pull = require('pull-stream')
var toPull = require('stream-to-pull-stream')
var split = require('split')

var count = 0
 
process.stdout.on('error', function( err ) {
  if (err.code == "EPIPE") {
    process.exit(1);
  }
});

pull(
    toPull.source(process.stdin.pipe(split())),
    pull.map(function (x) { 
        var c = count++
        if (c*c === Number.parseInt(x)) 
            return x
        else if (x === '') {
            process.exit(0)
        } else {
            process.stderr.write('error got ' +  x + ' instead of ' + c*c + '\n')
            process.exit(1)
        }
    }),
    pull.map(function (x) { return String(x) + '\n' }),
    toPull.sink(process.stdout)
)
