#!/usr/bin/env node

var pull = require('pull-stream')
var toPull = require('stream-to-pull-stream')
var split = require('split')

var count = 0

pull(
    toPull.source(process.stdin.pipe(split())),
    pull.map(function (x) { 
        var c = count++
        if (c*c === Number.parseInt(x)) 
            return x
        else {
            console.error('error got ' +  x + ' instead of ' + c*c)
            process.exit(1)
        }
    }),
    pull.map(function (x) { return String(x) + '\n' }),
    toPull.sink(process.stdout)
)
