#!/usr/bin/env node
try {
var electron = require('electron')
var BrowserWindow = electron.BrowserWindow

var n = process.argv[2] || 1
var url = process.argv[3] || 'http://localhost:5000'
var windows = new Array(n)

electron.app.on('ready', function () {
    for (var i = 0; i < n; ++i) {
      //setTimeout(function () {
        windows[i] = (new BrowserWindow({ show: false, webPreferrences: { offscreen: true } }))
        windows[i].loadURL(url)
      //}, Math.random() * 1000 + 500)
    }
})

process.on('SIGINT', function() {
    console.log("Caught interrupt signal");
    windows.forEach(function (w) {
        w.close()
    })
    process.exit();
});
} catch (e) {
    console.error(e)
}
